# Generated by Django 4.2.2 on 2023-07-12 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('CA', 'Current'), ('SA', 'Savings'), ('L', 'Loan'), ('FD', 'Fixed Deposit'), ('O', 'Other')], default='CA', max_length=2)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='banks.banks')),
            ],
        ),
    ]
