# Generated by Django 4.1.3 on 2023-06-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('CA', 'Current'), ('SA', 'Savings'), ('L', 'Loan'), ('FD', 'Fixed Deposit'), ('O', 'Other')], default='CA', max_length=2)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
