# Generated by Django 4.2.2 on 2023-07-10 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='user',
            field=models.ManyToManyField(related_name='user_bank', to=settings.AUTH_USER_MODEL),
        ),
    ]
