# Generated by Django 4.2.2 on 2023-07-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='user',
        ),
    ]
